name: 'Terraform'
 
on:
  push:
    paths:
    - terraform/**
    branches:
    - main
  pull_request:
    paths:
    - terraform/**
    branches:
    - main
 
jobs:
  validate-and-plan:
    name: Validate and Plan
    env:
      ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZ_TF_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZ_TF_CLIENT_SECRET }}
    runs-on: ubuntu-latest
    # environment: production
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2 

    - name: Terraform setup
      uses: hashicorp/setup-terraform@v2
    
    - run: formatCheck=$(terraform fmt -check)
    - run:
        if ! test -z "$formatCheck"; then 
        echo -e "Run terraform fmt to format\n$formatCheck";
        exit 1;
        fi
    - run: terraform init -input=false
    - run: terraform plan -out=tfplan -input=false

    - name: Upload Terraform plan
      uses: actions/upload-artifact@v3
      with:
        name: tfplan
        path: tfplan

  apply:
    name: 'Apply'
    needs: [validate-and-plan]
    env:
      ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZ_TF_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZ_TF_CLIENT_SECRET }}
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v2 
    
    - name: Download Terraform plan
      uses: actions/download-artifact@v3
      with:
        name: tfplan

    - name: 'Terraform setup'
      uses: hashicorp/setup-terraform@v2

    - run: terraform init
    - run: terraform apply
    