name: 'Terraform'
 
on:
  push:
    paths:
    - terraform/**
    branches:
    - main
  pull_request:
    paths:
    - terraform/**
    branches:
    - main
 
jobs:
  validate-and-plan:
    name: Validate and Plan
    env:
      ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZ_TF_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZ_TF_CLIENT_SECRET }}
    runs-on: ubuntu-latest
    # environment: production
 
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2 

    # Set up Terraform
    - name: Terraform setup
      uses: hashicorp/setup-terraform@v2
    
    # Initialize Terraform and generate plan
    - run: terraform init
    - run: terraform plan -input=false -out=tfplan

    # Upload Terraform plan to artifacts (to be used in apply job)
    - name: Upload Terraform plan
      uses: actions/upload-artifact@v3
      with:
        name: tfplan
        path: tfplan

    - run: ls -a

  # apply:
  #   name: Apply
  #   needs: [validate-and-plan]
  #   env:
  #     ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
  #     ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
  #     ARM_CLIENT_ID: ${{ secrets.AZ_TF_CLIENT_ID }}
  #     ARM_CLIENT_SECRET: ${{ secrets.AZ_TF_CLIENT_SECRET }}
  #   runs-on: ubuntu-latest
  #   environment: production

  #   defaults:
  #     run:
  #       shell: bash
  #       working-directory: ./terraform

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2 
    
  #   # Download previously-generated plan file from artifacts
  #   - name: Download Terraform plan
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: tfplan

  #   - name: 'Terraform setup'
  #     uses: hashicorp/setup-terraform@v2

  #   # Initialize Terraform and apply changes based on plan file
  #   - run: terraform init
  #   - run: terraform apply -input=false tfplan
    